export const name = '';
export const prefix = '';
export const owner = '';
export const invite_url = '';
export const github = 'https://github.com/theRealAyan/mitsuha-project';
export const token = '';
export const version = '<bot version>';
export const tscV = '<TS version>';
export const instance = { dev: true };
